name: base_project
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.2.19
  cupertino_icons: 1.0.2
  slang: 3.14.0
  logger: 1.3.0
  flutter_bloc: 8.1.3
  injectable: 2.1.0
  get_it: 7.2.0
  auto_route: ^7.1.0
  flutter_dotenv: 5.1.0
  equatable: 2.0.5
  retrofit: 4.0.1
  dio: 5.2.1+1
  pretty_dio_logger: ^1.3.1
  flutter_screenutil: ^5.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  dart_code_metrics: 5.7.2
  build_runner: 2.3.3
  flutter_gen_runner: 5.2.0
  auto_route_generator: ^7.0.0
  injectable_generator: 2.1.4
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  slang_build_runner: 3.14.0
  slang_flutter: 3.14.0
  retrofit_generator: 6.0.0+1
  json_serializable: 6.6.1

  #  export PATH=/Users/ducnguyenvan/Downloads/SDK/flutter/bin:$PATH


flutter_gen:
  output: lib/resource/generated
  line_length: 160
  null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true

flutter:
  uses-material-design: true
  # generate: false
  assets:
    - assets/images/
    - assets/env/