name: base_project
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: 2.2.19
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/images/among_icon.png
  android: false

  #  export PATH=/Users/ducnguyenvan/Downloads/SDK/flutter/bin:$PATH


flutter:
  uses-material-design: true
  # generate: false
  assets:
    - assets/images/