name: base_project
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.2.19
  cupertino_icons: ^1.0.2
  slang: ^3.14.0
  slang_flutter: ^3.14.0
  logger: ^1.3.0
  flutter_bloc: 8.1.2
  injectable: ^2.1.0
  get_it: ^7.2.0
  injectable_generator: ^2.1.4
  flutter_downloader: ^1.10.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  slang_build_runner: ^3.14.0
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  #  export PATH=/Users/ducnguyenvan/Downloads/SDK/flutter/bin:$PATH


flutter:
  uses-material-design: true
  # generate: false
  assets:
    - assets/images/